### ISSUE TITLE
Error when running the example data: floating-point exception

### ISSUE THREAD

**Issue by livipeluso** [beatrixparis/connectivity-modeling-system#40]
Hello everyone,

I'm new at CMS and I hope someone could help me with an error I'm getting when I try to run cms for the example data.

I installed CMS following the tutorial and at first I got some problems with the archive netcdf.mod, but I managed to solve it and installation appears to be ok.
When I run the test with the example data to verify it, getdata run without a problem and download the .nc files. However, when I try to run cms, this error appears:

$ ./cms example
 ==========================================
 File name  : traj_file_1
 Total number of release events     : 3 (numbers 1 to 3)
 Total number of particles released : 30
 Total number of time steps         : 289
 Total number of time steps in output file: 11
 ==========================================

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f7a52ca4d01 in ???
#1  0x7f7a52ca3ed5 in ???
#2  0x7f7a5290820f in ???
#3  0x559feef5d5b4 in ???
#4  0x559feef969f3 in ???
#5  0x559feef96a4c in ???
#6  0x7f7a528e90b2 in ???
#7  0x559feef3464d in ???
#8  0xffffffffffffffff in ???
Floating point exception (core dumped)

I searched for this error on google and the suggestions I found concern changing parameters of the model (reference values different from zero, boundary conditions or time step length) so that no divisions by 0 occur. However, I believe these do not apply to my case since I'm trying to run the example..
I found the CMS google group and some notes concerning installation in https://groups.google.com/g/connectivity-modeling-system-club/c/67kpxJTIHHo/m/6GruB75dAAAJ. I thought something might have gone wrong with the installation, so I tried to install everything again and this time I also installed some packages I didn't have that were on these notes (zlib and hdf5-tools). I run make again, getdata works, but when I run cms I get the same error.. I also tried to comment the mpi lines to see if the problem was associated with it, but I get the same error.

If anyone could help me with this, I would really really appreciate it! Thanks in advance!

Saludos

Lívia Peluso

**Comment by Yuma248** [comment]
The same problem here, after installing and reinstalling the package I got the same error, I wonder if this problem is related to the warning below: 


loop.f90:248:43:

  243 |            particle(r)%ndepth(n),startsec,particle(r)%diam(n), &
      |                                          2
......
  248 |            particle(r)%ndepth(n), startsec,-1, &
      |                                           1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(4)/REAL(4)).

**Comment by Yuma248** [comment]
This work for me

after running make with this error, I run 

mpif90 -c loop.f90 -I/folder/with/include -w -fallow-argument-mismatch -O2
make

**Comment by majambo** [comment]
> Hello everyone,
> 
> I'm new at CMS and I hope someone could help me with an error I'm getting when I try to run cms for the example data.
> 
> I installed CMS following the tutorial and at first I got some problems with the archive netcdf.mod, but I managed to solve it and installation appears to be ok. When I run the test with the example data to verify it, getdata run without a problem and download the .nc files. However, when I try to run cms, this error appears:
> 
> # $ ./cms example
> # File name : traj_file_1
> Total number of release events : 3 (numbers 1 to 3)
> Total number of particles released : 30
> Total number of time steps : 289
> Total number of time steps in output file: 11
> Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
> 
> Backtrace for this error: #0 0x7f7a52ca4d01 in ??? #1 0x7f7a52ca3ed5 in ??? #2 0x7f7a5290820f in ??? #3 0x559feef5d5b4 in ??? #4 0x559feef969f3 in ??? #5 0x559feef96a4c in ??? #6 0x7f7a528e90b2 in ??? #7 0x559feef3464d in ??? #8 0xffffffffffffffff in ??? Floating point exception (core dumped)
> 
> I searched for this error on google and the suggestions I found concern changing parameters of the model (reference values different from zero, boundary conditions or time step length) so that no divisions by 0 occur. However, I believe these do not apply to my case since I'm trying to run the example.. I found the CMS google group and some notes concerning installation in https://groups.google.com/g/connectivity-modeling-system-club/c/67kpxJTIHHo/m/6GruB75dAAAJ. I thought something might have gone wrong with the installation, so I tried to install everything again and this time I also installed some packages I didn't have that were on these notes (zlib and hdf5-tools). I run make again, getdata works, but when I run cms I get the same error.. I also tried to comment the mpi lines to see if the problem was associated with it, but I get the same error.
> 
> If anyone could help me with this, I would really really appreciate it! Thanks in advance!
> 
> Saludos
> 
> Lívia Peluso


Hi Livia,

I am getting the same error on multiple machines and I was wondering if you managed to get the model run!

Thanks

**Comment by silvaglx** [comment]
Any updates on this? Also trying to run the example simulation and facing the same error.
